config/routes.rb
Rails.application.routes.draw do

  resources :source_types
  resources :contracts
  resources :work_diaries
  resources :usage_sources
  resources :sources
  resources :employees
  resources :cadastral_offices
  resources :townships
  resources :customers
  resources :invoices
  resources :order_ways
  resources :order_types
  resources :handover_ways
  resources :price_creations

  root 'welcome#index'

end

app/models/cadastral_office.rb
class CadastralOffice < ActiveRecord::Base
  has_many :contracts
end

app/models/contract.rb
class Contract < ActiveRecord::Base
  belongs_to :customer
  belongs_to :cadastral_office
  belongs_to :township
  belongs_to :responsible
  belongs_to :bend_1
  belongs_to :bend_2
  belongs_to :drawed_up
  belongs_to :checked
  belongs_to :screened
  belongs_to :order_way
  belongs_to :order_type
  belongs_to :handover_way
  belongs_to :price_creation
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :contracts
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :contracts, foreign_key: "responsible_id"
  has_many :contracts, foreign_key: "bend_1_id"
  has_many :contracts, foreign_key: "bend_2_id"
  has_many :contracts, foreign_key: "drawed_up_id"
  has_many :contracts, foreign_key: "checked_id"
  has_many :contracts, foreign_key: "screened_id"
  has_many :work_diary
  has_many :usage_sources
end

app/models/handover_way.rb
class HandoverWay < ActiveRecord::Base
  has_many :contracts
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :contract
end

app/models/order_type.rb
class OrderType < ActiveRecord::Base
  has_many :contracts
end

app/models/order_way.rb
class OrderWay < ActiveRecord::Base
  has_many :contracts
end

app/models/price_creation.rb
class PriceCreation < ActiveRecord::Base
  has_many :contracts
end

app/models/source.rb
class Source < ActiveRecord::Base
  belongs_to :source_type
end

app/models/source_type.rb
class SourceType < ActiveRecord::Base
  has_many :sources

  accepts_nested_attributes_for :sources
end

app/models/township.rb
class Township < ActiveRecord::Base
  has_many :contracts
end

app/models/usage_source.rb
class UsageSource < ActiveRecord::Base
  belongs_to :source
  belongs_to :contract
  belongs_to :employee
end

app/models/work_diary.rb
class WorkDiary < ActiveRecord::Base
  belongs_to :employee
  belongs_to :contract
end

app/controllers/source_types_controller.rb
class SourceTypesController < ApplicationController
  before_action :set_source_type, only: [:show, :edit, :update, :destroy]

  # GET /source_types
  # GET /source_types.json
  def index
    @source_types = SourceType.all
  end

  # GET /source_types/1
  # GET /source_types/1.json
  def show
    @submit_value = "Show"
    @hidden_submit = "hidden"
  end

  # GET /source_types/new
  def new
    @source_type = SourceType.new
    @submit_value = "Create"
    @hidden_submit = ""
  end

  # GET /source_types/1/edit
  def edit
    @submit_value = "Update"
    @hidden_submit = ""
  end

  # POST /source_types
  # POST /source_types.json
  def create
    @source_type = SourceType.new(source_type_params)
    respond_to do |format|
      if @source_type.save
        format.html { redirect_to @source_type, notice: 'Source type was successfully created.' }
        format.json { render :show, status: :created, location: @source_type }
      else
        format.html { render :new }
        format.json { render json: @source_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /source_types/1
  # PATCH/PUT /source_types/1.json
  def update
    respond_to do |format|
      if @source_type.update(source_type_params)
        format.html { redirect_to @source_type, notice: 'Source type was successfully updated.' }
        format.json { render :show, status: :ok, location: @source_type }
      else
        format.html { render :edit }
        format.json { render json: @source_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /source_types/1
  # DELETE /source_types/1.json
  def destroy
    if !@source_type.sources.any?
      @source_type.destroy
      respond_to do |format|
        format.html { redirect_to source_types_url, notice: 'Source type was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to source_type_url, notice: 'Source type has sources, yet. Destroy the sources before.' }
        format.json { render json: @source_type.errors, status: :unprocessable_entity }
      end
    end  
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_source_type
      @source_type = SourceType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def source_type_params
      params.require(:source_type).permit(:name)
    end
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/source_types_helper.rb
module SourceTypesHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/source_types/_form.html.erb
<%= form_for(@source_type) do |f| %>
  <% if @source_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@source_type.errors.count, "error") %> prohibited this source_type from being saved:</h2>

      <ul>
      <% @source_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    &nbsp;<br>
  </div>

  <div>
    <%= f.label t(:Name) %><br>
    <%= f.text_field :name %>
  </div>

  <div>
    &nbsp;<br>
  </div>

  <div class="actions" <%= @hidden_submit %> >
    <%= submit_tag t(@submit_value) %>
  </div>

  <div>
    &nbsp;<br>
  </div>

<% end %>

app/views/source_types/edit.html.erb
<h2><%=t :Editing %>&nbsp;<%=t :source_type_u %></h2>

<%= render 'form' %>

<%= link_to t('Home'), root_path %>&nbsp;&nbsp;&nbsp;
<%= link_to t('Show'), @source_type %>&nbsp;&nbsp;&nbsp;
<%= link_to t('List'), source_types_path %>

app/views/source_types/index.html.erb
<h2><%=t :Listing %>&nbsp;<%=t :source_types %></h2>

<table cellspacing=15 >
  <tr>
    <td><%=t 'Name' %></td>
  </tr>
  <% @source_types.each do |source_type| %>
    <tr>
      <td><%= source_type.name %></td>
      <td><%= link_to t('Show'), source_type %></td>
      <td><%= link_to t('Edit'), edit_source_type_path(source_type) %></td>
      <td><%= link_to t('Destroy'), source_type, method: :delete, data: { confirm: t('Are_you_sure?') } %></td>
    </tr>
  <% end %>
</table>

<br>

&nbsp;&nbsp;&nbsp;<%= link_to t('Home'), root_path %>
&nbsp;&nbsp;&nbsp;<%= link_to t('New'), new_source_type_path %>

app/views/source_types/new.html.erb
<h2><%=t :New %>&nbsp;<%=t :source_type %></h2>

<%= render 'form' %>

<%= link_to t('Home'), root_path %>&nbsp;&nbsp;&nbsp;
<%= link_to t('List'), source_types_path %>

app/views/source_types/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%=t :Showing %>&nbsp;<%=t :source_type_u %></h2>

<%= render 'form' %>

<%= link_to t('Home'), root_path %>&nbsp;&nbsp;&nbsp;
<%= link_to t('Edit'), edit_source_type_path(@source_type) %>&nbsp;&nbsp;&nbsp;
<%= link_to t('List'), source_types_path %>&nbsp;&nbsp;&nbsp;
<%= link_to t('Source_List'), sources_path %>