config/routes.rb
Rails.application.routes.draw do

  resources :source_types
  resources :contracts
  resources :work_diaries
  resources :usage_sources
  resources :sources
  resources :employees
  resources :cadastral_offices
  resources :townships
  resources :customers
  resources :invoices
  resources :order_ways
  resources :order_types
  resources :handover_ways
  resources :price_creations

  root 'welcome#index'

end

app/models/cadastral_office.rb
class CadastralOffice < ActiveRecord::Base
  has_many :contracts
end

app/models/contract.rb
class Contract < ActiveRecord::Base
  belongs_to :customer
  belongs_to :cadastral_office
  belongs_to :township
  belongs_to :responsible
  belongs_to :bend_1
  belongs_to :bend_2
  belongs_to :drawed_up
  belongs_to :checked
  belongs_to :screened
  belongs_to :order_way
  belongs_to :order_type
  belongs_to :handover_way
  belongs_to :price_creation
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :contracts
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :contracts, foreign_key: "responsible_id"
  has_many :contracts, foreign_key: "bend_1_id"
  has_many :contracts, foreign_key: "bend_2_id"
  has_many :contracts, foreign_key: "drawed_up_id"
  has_many :contracts, foreign_key: "checked_id"
  has_many :contracts, foreign_key: "screened_id"
  has_many :work_diary
  has_many :usage_sources
end

app/models/handover_way.rb
class HandoverWay < ActiveRecord::Base
  has_many :contracts
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :contract
end

app/models/order_type.rb
class OrderType < ActiveRecord::Base
  has_many :contracts
end

app/models/order_way.rb
class OrderWay < ActiveRecord::Base
  has_many :contracts
end

app/models/price_creation.rb
class PriceCreation < ActiveRecord::Base
  has_many :contracts
end

app/models/source.rb
class Source < ActiveRecord::Base
  belongs_to :source_type
end

app/models/source_type.rb
class SourceType < ActiveRecord::Base
  has_many :sources

  accepts_nested_attributes_for :sources
end

app/models/township.rb
class Township < ActiveRecord::Base
  has_many :contracts
end

app/models/usage_source.rb
class UsageSource < ActiveRecord::Base
  belongs_to :source
  belongs_to :contract
  belongs_to :employee
end

app/models/work_diary.rb
class WorkDiary < ActiveRecord::Base
  belongs_to :employee
  belongs_to :contract
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/helpers/townships_helper.rb
module TownshipsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<h2><%= t(:Contracts) %> - N&Z Geodet</h2>

<table cellspacing=15>
	<tr>
	  <td>
		<%=t :Contract %>:
	  </td>
	  <td>
	  	<%= link_to t('New_a'), new_contract_path %>
	  </td>
	  <td>
	  	<%= link_to t('List'), contracts_path %>
	  </td>
	  <td>&nbsp;&nbsp;&nbsp;</td>
	  <td>
		<%=t :Work %> <%=t :diary %>:
	  </td>
	  <td>
		<%= link_to t('New'), new_work_diary_path %>
	  </td>
	  <td>
		<%= link_to t('List'), work_diaries_path %>
	  </td>
	</tr>
	<tr>
	  <td>
		<%=t :Employee %>:
	  </td>
	  <td>
	  	<%= link_to t('New'), new_employee_path %>
	  </td>
	  <td>
	  	<%= link_to t('List'), employees_path %>
	  </td>
	  <td>&nbsp;&nbsp;&nbsp;</td>
	  <td>
		<%=t :Usage %> <%=t :source_u %>:
	  </td>
	  <td>
	  	<%= link_to t('New'), new_usage_source_path %>
	  </td>
	  <td>
	  	<%= link_to t('List'), usage_sources_path %>
	  </td>
	</tr>
	<tr>
	  <td>
		<%=t :Customer %>:
	  </td>
	  <td>
	  	<%= link_to t('New'), new_customer_path %>
	  </td>
	  <td>
	  	<%= link_to t('List'), customers_path %>
	  </td>
	</tr>
	<tr>
	  <td>
		<%=t :Type %> <%=t :source_u %>:
	  </td>
	  <td>
	  	<%= link_to t('New'), new_source_type_path %>
	  </td>
	  <td>
	  	<%= link_to t('List'), source_types_path %>
	  </td>
	</tr>
	<tr>
	  <td>
		<%=t :Source %>:
	  </td>
	  <td>
	  	<%= link_to t('New'), new_source_path %>
	  </td>
	  <td>
	  	<%= link_to t('List'), sources_path %>
	  </td>
	</tr>
	<tr>
	  <td>
		<%=t :Township %>:
	  <td>
	  	<%= link_to t('New_a'), new_township_path %>
	  </td>
	  <td>
	  	<%= link_to t('List'), townships_path %>
	  </td>
	</tr>
	<tr>
	  <td>
		<%=t :Cadastral %> <%=t :Office %>:
	  </td>
	  <td>
	  	<%= link_to t('New'), new_cadastral_office_path %>
	  </td>
	  <td>
	  	<%= link_to t('List'), cadastral_offices_path %>
	  </td>
	</tr>
	<tr>
	  <td>
		<%=t :Handover_way %>:
	  </td>
	  <td>
	  	<%= link_to t('New'), new_handover_way_path %>
	  </td>
	  <td>
	  	<%= link_to t('List'), handover_ways_path %>
	  </td>
	</tr>
	<tr>
	  <td>
		<%=t :Invoice %>:
	  </td>
	  <td>
	  	<%= link_to t('New_a'), new_invoice_path %>
	  </td>
	  <td>
	  	<%= link_to t('List'), invoices_path %>
	  </td>
	</tr>
	<tr>
	  <td>
		<%=t :Order_type %>:
	  </td>
	  <td>
	  	<%= link_to t('New'), new_order_type_path %>
	  </td>
	  <td>
	  	<%= link_to t('List'), order_types_path %>
	  </td>
	</tr>
	<tr>
	  <td>
		<%=t :Order_way %>:
	  </td>
	  <td>
	  	<%= link_to t('New'), new_order_way_path %>
	  </td>
	  <td>
	  	<%= link_to t('List'), order_ways_path %>
	  </td>
	</tr>
	<tr>
	  <td>
		<%=t :Price_creation %>:
	  </td>
	  <td>
	  	<%= link_to t('New_a'), new_price_creation_path %>
	  </td>
	  <td>
	  	<%= link_to t('List'), price_creations_path %>
	  </td>
	</tr>
</table>