config/routes.rb
Rails.application.routes.draw do

  resources :source_types
  resources :contracts
  resources :work_diaries
  resources :usage_sources
  resources :sources
  resources :employees
  resources :cadastral_offices
  resources :townships
  resources :customers
  resources :invoices
  resources :order_ways
  resources :order_types
  resources :handover_ways
  resources :price_creations

  root 'welcome#index'

end

app/models/cadastral_office.rb
class CadastralOffice < ActiveRecord::Base
  has_many :contracts
end

app/models/contract.rb
class Contract < ActiveRecord::Base
  belongs_to :customer
  belongs_to :cadastral_office
  belongs_to :township
  belongs_to :responsible
  belongs_to :bend_1
  belongs_to :bend_2
  belongs_to :drawed_up
  belongs_to :checked
  belongs_to :screened
  belongs_to :order_way
  belongs_to :order_type
  belongs_to :handover_way
  belongs_to :price_creation
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :contracts
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :contracts, foreign_key: "responsible_id"
  has_many :contracts, foreign_key: "bend_1_id"
  has_many :contracts, foreign_key: "bend_2_id"
  has_many :contracts, foreign_key: "drawed_up_id"
  has_many :contracts, foreign_key: "checked_id"
  has_many :contracts, foreign_key: "screened_id"
  has_many :work_diary
  has_many :usage_sources
end

app/models/handover_way.rb
class HandoverWay < ActiveRecord::Base
  has_many :contracts
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :contract
end

app/models/order_type.rb
class OrderType < ActiveRecord::Base
  has_many :contracts
end

app/models/order_way.rb
class OrderWay < ActiveRecord::Base
  has_many :contracts
end

app/models/price_creation.rb
class PriceCreation < ActiveRecord::Base
  has_many :contracts
end

app/models/source.rb
class Source < ActiveRecord::Base
  belongs_to :source_type
end

app/models/source_type.rb
class SourceType < ActiveRecord::Base
  has_many :sources

  accepts_nested_attributes_for :sources
end

app/models/township.rb
class Township < ActiveRecord::Base
  has_many :contracts
end

app/models/usage_source.rb
class UsageSource < ActiveRecord::Base
  belongs_to :source
  belongs_to :contract
  belongs_to :employee
end

app/models/work_diary.rb
class WorkDiary < ActiveRecord::Base
  belongs_to :employee
  belongs_to :contract
end

app/controllers/cadastral_offices_controller.rb
class CadastralOfficesController < ApplicationController
  before_action :set_cadastral_office, only: [:show, :edit, :update, :destroy]

  # GET /cadastral_offices
  # GET /cadastral_offices.json
  def index
    @cadastral_offices = CadastralOffice.all
  end

  # GET /cadastral_offices/1
  # GET /cadastral_offices/1.json
  def show
    @submit_value = "Show"
    @hidden_submit = "hidden"
  end

  # GET /cadastral_offices/new
  def new
    @cadastral_office = CadastralOffice.new
    @submit_value = "Create"
    @hidden_submit = ""
  end

  # GET /cadastral_offices/1/edit
  def edit
    @submit_value = "Update"
    @hidden_submit = ""
  end

  # POST /cadastral_offices
  # POST /cadastral_offices.json
  def create
    @cadastral_office = CadastralOffice.new(cadastral_office_params)

    respond_to do |format|
      if @cadastral_office.save
        format.html { redirect_to @cadastral_office, notice: 'Cadastral office was successfully created.' }
        format.json { render :show, status: :created, location: @cadastral_office }
      else
        format.html { render :new }
        format.json { render json: @cadastral_office.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cadastral_offices/1
  # PATCH/PUT /cadastral_offices/1.json
  def update
    respond_to do |format|
      if @cadastral_office.update(cadastral_office_params)
        format.html { redirect_to @cadastral_office, notice: 'Cadastral office was successfully updated.' }
        format.json { render :show, status: :ok, location: @cadastral_office }
      else
        format.html { render :edit }
        format.json { render json: @cadastral_office.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cadastral_offices/1
  # DELETE /cadastral_offices/1.json
  def destroy
    @cadastral_office.destroy
    respond_to do |format|
      format.html { redirect_to cadastral_offices_url, notice: 'Cadastral office was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cadastral_office
      @cadastral_office = CadastralOffice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cadastral_office_params
      params.require(:cadastral_office).permit(:name)
    end
end

app/helpers/cadastral_offices_helper.rb
module CadastralOfficesHelper
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/helpers/townships_helper.rb
module TownshipsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cadastral_offices/_form.html.erb
<%= form_for(@cadastral_office) do |f| %>
  <% if @cadastral_office.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cadastral_office.errors.count, "error") %> prohibited this cadastral_office from being saved:</h2>

      <ul>
      <% @cadastral_office.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    &nbsp;<br>
  </div>

  <div>
    <%= f.label t(:Name) %><br>
    <%= f.text_field :name %>
  </div>

  <div>
    &nbsp;<br>
  </div>

  <div class="actions" <%= @hidden_submit %> >
    <%= submit_tag t(@submit_value) %>
  </div>

  <div>
    &nbsp;<br>
  </div>

<% end %>

app/views/cadastral_offices/edit.html.erb
<h2><%=t :Editing %>&nbsp;<%=t :cadastral_office_u %></h2>

<%= render 'form' %>

<%= link_to t('Home'), root_path %>&nbsp;&nbsp;&nbsp;
<%= link_to t('Show'), @cadastral_office %>&nbsp;&nbsp;&nbsp;
<%= link_to t('List'), cadastral_offices_path %>

app/views/cadastral_offices/index.html.erb
<h2><%=t :Listing %>&nbsp;<%=t :cadastral_offices %></h2>

<table cellspacing=15 >
  <tr>
    <td><%=t 'name' %></td>
  </tr>
  <% @cadastral_offices.each do |cadastral_office| %>
    <tr>
      <td><%= cadastral_office.name %></td>
      <td><%= link_to t('Show'), cadastral_office %></td>
      <td><%= link_to t('Edit'), edit_cadastral_office_path(cadastral_office) %></td>
      <td><%= link_to t('Destroy'), cadastral_office, method: :delete, data: { confirm: t('Are_you_sure?') } %></td>
    </tr>
  <% end %>
</table>

<br>

&nbsp;&nbsp;&nbsp;<%= link_to t('Home'), root_path %>
&nbsp;&nbsp;&nbsp;<%= link_to t('New'), new_cadastral_office_path %>

app/views/cadastral_offices/new.html.erb
<h2><%=t :New %>&nbsp;<%=t :cadastral_office %></h2>

<%= render 'form' %>

<%= link_to t('Home'), root_path %>&nbsp;&nbsp;&nbsp;
<%= link_to t('List'), cadastral_offices_path %>

app/views/cadastral_offices/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%=t :Showing %>&nbsp;<%=t :cadastral_office_u %></h2>

<%= render 'form' %>


<%= link_to t('Home'), root_path %>&nbsp;&nbsp;&nbsp;
<%= link_to t('Edit'), edit_cadastral_office_path(@cadastral_office) %>&nbsp;&nbsp;&nbsp;
<%= link_to t('List'), cadastral_offices_path %>