config/routes.rb
Rails.application.routes.draw do

  resources :source_types
  resources :contracts
  resources :work_diaries
  resources :usage_sources
  resources :sources
  resources :employees
  resources :cadastral_offices
  resources :townships
  resources :customers
  resources :invoices
  resources :order_ways
  resources :order_types
  resources :handover_ways
  resources :price_creations

  root 'welcome#index'

end

app/models/cadastral_office.rb
class CadastralOffice < ActiveRecord::Base
  has_many :contracts
end

app/models/contract.rb
class Contract < ActiveRecord::Base
  belongs_to :customer
  belongs_to :cadastral_office
  belongs_to :township
  belongs_to :responsible
  belongs_to :bend_1
  belongs_to :bend_2
  belongs_to :drawed_up
  belongs_to :checked
  belongs_to :screened
  belongs_to :order_way
  belongs_to :order_type
  belongs_to :handover_way
  belongs_to :price_creation
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :contracts
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :contracts, foreign_key: "responsible_id"
  has_many :contracts, foreign_key: "bend_1_id"
  has_many :contracts, foreign_key: "bend_2_id"
  has_many :contracts, foreign_key: "drawed_up_id"
  has_many :contracts, foreign_key: "checked_id"
  has_many :contracts, foreign_key: "screened_id"
  has_many :work_diary
  has_many :usage_sources
end

app/models/handover_way.rb
class HandoverWay < ActiveRecord::Base
  has_many :contracts
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :contract
end

app/models/order_type.rb
class OrderType < ActiveRecord::Base
  has_many :contracts
end

app/models/order_way.rb
class OrderWay < ActiveRecord::Base
  has_many :contracts
end

app/models/price_creation.rb
class PriceCreation < ActiveRecord::Base
  has_many :contracts
end

app/models/source.rb
class Source < ActiveRecord::Base
  belongs_to :source_type
end

app/models/source_type.rb
class SourceType < ActiveRecord::Base
  has_many :sources

  accepts_nested_attributes_for :sources
end

app/models/township.rb
class Township < ActiveRecord::Base
  has_many :contracts
end

app/models/usage_source.rb
class UsageSource < ActiveRecord::Base
  belongs_to :source
  belongs_to :contract
  belongs_to :employee
end

app/models/work_diary.rb
class WorkDiary < ActiveRecord::Base
  belongs_to :employee
  belongs_to :contract
end

app/controllers/usage_sources_controller.rb
class UsageSourcesController < ApplicationController
  before_action :set_usage_source, only: [:show, :edit, :update, :destroy]
  before_action :set_source, only: [:show, :new, :edit]

  # GET /usage_sources
  # GET /usage_sources.json
  def index
    @usage_sources = UsageSource.all
  end

  # GET /usage_sources/1
  # GET /usage_sources/1.json
  def show
    @employees = Employee.all
    @contracts = Contract.all
    @from = @usage_source.from
    @to = @usage_source.to
    @submit_value = "Show"
    @hidden_submit = "hidden"
  end

  # GET /usage_sources/new
  def new
    @usage_source = UsageSource.new
    @employees = Employee.all
    @contracts = Contract.all
    @from = Time.now
    @to = Time.now
    @submit_value = "Create"
    @hidden_submit = ""
  end

  # GET /usage_sources/1/edit
  def edit
    @employees = Employee.all
    @contracts = Contract.all
    @from = @usage_source.from
    @to = @usage_source.to
    @submit_value = "Update"
    @hidden_submit = ""
  end

  # POST /usage_sources
  # POST /usage_sources.json
  def create
    @usage_source = UsageSource.new(usage_source_params)

    respond_to do |format|
      if @usage_source.save
        format.html { redirect_to @usage_source, notice: 'Usage source was successfully created.' }
        format.json { render :show, status: :created, location: @usage_source }
      else
        format.html { render :new }
        format.json { render json: @usage_source.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usage_sources/1
  # PATCH/PUT /usage_sources/1.json
  def update
    respond_to do |format|
      if @usage_source.update(usage_source_params)
        format.html { redirect_to @usage_source, notice: 'Usage source was successfully updated.' }
        format.json { render :show, status: :ok, location: @usage_source }
      else
        format.html { render :edit }
        format.json { render json: @usage_source.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usage_sources/1
  # DELETE /usage_sources/1.json
  def destroy
    @usage_source.destroy
    respond_to do |format|
      format.html { redirect_to usage_sources_url, notice: 'Usage source was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usage_source
      @usage_source = UsageSource.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usage_source_params
      params.require(:usage_source).permit(:employee_id, :contract_id, 
        :source_id, :from, :to, :unit_number, :amount)
    end

    def set_source
      @sources = Source.all
      @sources.each do |source|
        appender = ""
        if source.description != ""
          appender = ": " + source.description
        end
        source.description = (SourceType.find(source.source_type_id).name + appender)
      end
    end
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/helpers/townships_helper.rb
module TownshipsHelper
end

app/helpers/usage_sources_helper.rb
module UsageSourcesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/usage_sources/_form.html.erb
<%= form_for(@usage_source) do |f| %>
  <% if @usage_source.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usage_source.errors.count, "error") %> prohibited this usage_source from being saved:</h2>

      <ul>
      <% @usage_source.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    &nbsp;<br>
  </div>

  <div>
    <%= f.label t(:Reported_by) %><br>
    <%= f.collection_select(:employee_id, @employees, :id, :name) %>
  </div>

  <div>
    &nbsp;<br>
  </div>

  <div>
    <%= f.label t(:Contract) %><br>
    <%= f.collection_select(:contract_id, @contracts, :id, :contract_number) %>
  </div>

  <div>
    &nbsp;<br>
  </div>

  <div>
    <%= f.label t(:Source) %><br>
    <%= f.collection_select(:source_id, @sources, :id, :description) %>
    <span <%= @hidden_submit %> >
      <%= link_to t('New'), new_source_path %>
    </span>
  </div>

  <div>
    &nbsp;<br>
  </div>

  <div>
    <%= f.label t(:From) %><br>
    <%= f.text_field :from, :value => @from %>
  </div>

  <div>
    &nbsp;<br>
  </div>

  <div>
    <%= f.label t(:To) %><br>
    <%= f.text_field :to, :value => @to %>
  </div>

  <div>
    &nbsp;<br>
  </div>

  <div>
    <%= f.label t(:Unit_number) %><br>
    <%= f.text_field :unit_number %>
  </div>

  <div>
    &nbsp;<br>
  </div>

  <div>
    <%= f.label t(:Amount) %><br>
    <%= f.text_field :amount %>
  </div>

  <div>
    &nbsp;<br>
  </div>

  <div class="actions" <%= @hidden_submit %> >
    <%= submit_tag t(@submit_value) %>
  </div>

  <div>
    &nbsp;<br>
  </div>

<% end %>

app/views/usage_sources/edit.html.erb
<h2><%=t :Editing %>&nbsp;<%=t :usage_source %></h2>

<%= render 'form' %>

<%= link_to t('Home'), root_path %>&nbsp;&nbsp;&nbsp;
<%= link_to t('Show'), @usage_source %>&nbsp;&nbsp;&nbsp;
<%= link_to t('List'), usage_sources_path %>

app/views/usage_sources/index.html.erb
<h2><%=t :Listing %>&nbsp;<%=t :usage_sources %></h2>

<table cellspacing=15 >
  <tr>
    <td><%=t t('Reported_by') %></td>
    <td><%=t t('Contract') %></td>
    <td><%=t t('Source') %></td>
    <td><%=t t('From') %></td>
    <td><%=t t('To') %></td>
    <td><%=t t('Unit_number') %></td>
    <td><%=t t('Amount') %></td>
  </tr>
  <% @usage_sources.each do |usage_source| 
    employee = Employee.find(usage_source.employee_id) 
    contract = Contract.find(usage_source.contract_id) 
    source = Source.find(usage_source.source_id)
    appender = ""
    if source.description != ""
      appender = ": " + source.description
    end
    %>
    <tr>
      <td><%= employee.name %></td>
      <td><%= contract.contract_number %></td>
      <td><%= SourceType.find(source.source_type_id).name + appender %></td>
      <td><%= usage_source.from %></td>
      <td><%= usage_source.to %></td>
      <td><%= usage_source.unit_number %></td>
      <td><%= usage_source.amount %></td>
      <td><%= link_to t('Show'), usage_source %></td>
      <td><%= link_to t('Edit'), edit_usage_source_path(usage_source) %></td>
      <td><%= link_to t('Destroy'), usage_source, method: :delete, data: { confirm: t('Are_you_sure?') } %></td>
    </tr>
  <% end %>
</table>

<br>

&nbsp;&nbsp;&nbsp;<%= link_to t('Home'), root_path %>
&nbsp;&nbsp;&nbsp;<%= link_to t('New'), new_usage_source_path %>

app/views/usage_sources/new.html.erb
<h2><%=t :New_e %>&nbsp;<%=t :usage_source %></h2>

<%= render 'form' %>

<%= link_to t('Home'), root_path %>&nbsp;&nbsp;&nbsp;
<%= link_to t('List'), usage_sources_path %>

app/views/usage_sources/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%=t :Showing %>&nbsp;<%=t :usage_source %></h2>

<%= render 'form' %>

<%= link_to t('Home'), root_path %>&nbsp;&nbsp;&nbsp;
<%= link_to t('Edit'), edit_usage_source_path(@usage_source) %>&nbsp;&nbsp;&nbsp;
<%= link_to t('List'), usage_sources_path %>